/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tic.tac.toe;

import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author khosali19
 */
public class MainJframe extends javax.swing.JFrame {
 private ArrayList<JPanel> panels;
    /**
     * Creates new form MainJframe
     */
    public MainJframe() {
        initComponents();
        int w = this.getWidth();
        int h = this.getHeight();
        panels = new ArrayList<JPanel>(); //creates ArrayList of JPanels
        
        HomeScreen j = new HomeScreen();
        panels.add(j);      
        this.add(j);
        j.setJf(this);
        
        MultiplayerScreen j2 = new MultiplayerScreen();
        panels.add(j2);
        this.add(j2);
        j2.setJf(this);
        
          ComputerScreen j3 = new ComputerScreen();
        panels.add(j3);
        this.add(j3);
        j3.setJf(this);
        
         MultiplayerPLAY j4 = new MultiplayerPLAY();
        panels.add(j4);
        this.add(j4);
        j4.setJf(this);
        
         this.pack();
        j.setLocation(0,0);
        j.setSize(1200, 1000);
        j.setVisible(true);
        
        j2.setLocation(0,0);
        j2.setSize(1200, 1000);
        j2.setVisible(true);
        
         j3.setLocation(0,0);
        j3.setSize(1200, 1000);
        j3.setVisible(true);
        
        j4.setLocation(0,0);
        j4.setSize(1200, 1000);
        j4.setVisible(true);
        
        showPanel(0);
    }

    public void showPanel(int panelNum) { //to show one JPanel at a time
        for (int i = 0; i < panels.size(); i++) {
            panels.get(i).setVisible(false);
        }
        //BasePanel currPanel = (BasePanel) panels.get(panelNum);
        //currPanel.refresh();
        panels.get(panelNum).setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
